version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: platform-spec
    main: ./cmd/platform-spec
    binary: platform-spec
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    # Only build darwin/arm64 and linux/amd64
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}

archives:
  - id: platform-spec
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*
    format_overrides:
      - goos: darwin
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: neilfarmer
    name: platform-spec
  draft: false
  prerelease: auto
